### PR TITLE
Move configs to Hiera, add PHP up to 5.4.36, 5.5.20 and 5.6.4, allow additional configure params on PHP builds, add Pthreads extension, warn user when installing insecure versions

### PR DESCRIPTION
**Pull request by sambauers**
To add configure params to a PHP version, all that needs to be done is to add the following to the Hiera yaml:

```
php::config::configure_params:
  5.5.18: '--enable-maintainer-zts'
```

This example will add ZTS support to PHP 5.5.18 - which allows the installation of the pthreads extension.

This does not allow multiple variants of the same version of PHP to be installed. i.e. you can't install 5.5.18 and 5.5.18 with ZTS.

### CODE REVIEW

**Comment by sambauers** [comment]
Broke your tests :grin:

I'll see if I can fix that.

**Comment by sambauers** [comment]
I've fixed the specs and added PHP 5.6.X

Fixing the specs required an update of Cardboard, and some deprecation fixes.

This PR is now a bit monolithic. Sorry about that.

**Comment by sambauers** [comment]
Have merged in latest changes on boxen/puppet-php and updated new specs there for newer version of Cardboard/RSpec methods.

**Comment by mattheath** [comment]
Fantastic work @sambauers, I'll try to have a proper look over the next couple of days!

**Comment by mattheath** [comment]
@sambauers apologies this has taken so long for me to get to. I'm still working through, but have a few thoughts:
- This is a huge (and awesome!) change, we should target a `2.0.0` release
- Not sure on the _secure version_ part? To me this adds additional maintenance, as we'll have to keep it up to date. Also as boxen targets developer machines, I'm not sure it's as important / worth it?
- Following on from the above, maintaining the PHP version and FPM classes is a pain, perhaps we should go the way the ruby and node modules have gone and ditch these?

I've pushed the latest master changes from this repo into the 'official' boxen repo so that it's up to date, and I've opened a [v2](https://github.com/boxen/puppet-php/tree/v2) branch over there. Sorry to ask, but could I get you to rebase onto 6639ee1e15febb4c1c2976fb0678ba2b46b69237 and open a PR there? Happy to do that if you need me to. Then we can merge this and any further changes and I'll cut beta tags until we're completely happy everything works (which I'm sure it already does!).

**Comment by sambauers** [comment]
Closing this. Will rebase against boxen/puppet-php v2 branch and make a new pull request against it.

**Pull request closed without merging**
