### PR TITLE
Add manifests for new php versions.

### PR DESCRIPTION
**Pull request by nathankot**

### CODE REVIEW

**Comment by webflo** [comment]
Can you also create fpm classes? https://github.com/mattheath/puppet-php/tree/master/manifests/fpm

Thanks!

**Comment by nathankot** [comment]
@webflo done :)

**Comment by webflo** [comment]
@mattheath could you merge this in boxen/puppet-php?

**Comment by mattheath** [comment]
Yep, thanks for this! :+1:

**Pull request merged**
